### ISSUE TITLE
[BUG] Cant't work in 1.12.2 - CatServer

### ISSUE THREAD

**Issue by 849025143** [CrazyCloudCraft/worldsystem-depecated#77]
[12:37:40] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\WorldSystem-2.4.34-dev3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `de.butzlabben.world.WorldSystem'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:88) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[JavaPluginLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[SimplePluginManager.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [SimplePluginManager.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:359) [CraftServer.class:git-CatServer-1.12.2-ab28211f]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:340) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:636) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_361]
Caused by: java.lang.ClassNotFoundException: Failed to remap class de.butzlabben.world.WorldSystem
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:231) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_361]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_361]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_361]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	... 8 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
	at net.md_5.specialsource.JarRemapper.remapClassFile(JarRemapper.java:228) ~[JarRemapper.class:?]
	at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:196) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:129) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_361]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_361]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_361]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:86) ~[PluginClassLoader.class:git-CatServer-1.12.2-ab28211f]
	... 8 more

**Comment by n1klasse** [comment]
Please use this version: https://github.com/Argantiu/WorldSystem-dev/releases/tag/v2.4.34-dev
